//===- LowerTimedProcesses.cpp - LLHD timed process to Seq -----------------===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// Lowers llhd.process operations with a single llhd.wait into Seq registers
// and combinational logic. Targets the code shape generated by ImportVerilog
// for always blocks: a state block terminated by a wait, a dest block that
// checks the trigger condition and loops back to the state block, and drives
// of module-level signals along the body. Processes that do not match this
// shape are left untouched so that callers can diagnose them.
//
// After the processes are lowered, module-level llhd.sig operations driven by
// the spliced process bodies are converted into clocked registers, while
// purely combinationally-driven signals become mux trees.
//
//===----------------------------------------------------------------------===//

#include "circt/Dialect/Comb/CombOps.h"
#include "circt/Dialect/HW/HWOps.h"
#include "circt/Dialect/LLHD/LLHDOps.h"
#include "circt/Dialect/LLHD/LLHDPasses.h"
#include "circt/Dialect/Seq/SeqOps.h"
#include "circt/Dialect/Sim/SimOps.h"
#include "mlir/Analysis/TopologicalSortUtils.h"
#include "mlir/Dialect/ControlFlow/IR/ControlFlowOps.h"
#include "mlir/IR/Builders.h"
#include "mlir/Pass/Pass.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/SmallVector.h"

namespace circt {
namespace llhd {
#define GEN_PASS_DEF_LOWERTIMEDPROCESSESPASS
#include "circt/Dialect/LLHD/LLHDPasses.h.inc"
} // namespace llhd
} // namespace circt

using namespace mlir;
using namespace circt;

namespace {

static Value constTrue(OpBuilder &builder, Location loc) {
  return builder.create<hw::ConstantOp>(loc, APInt(1, 1));
}

/// Compute, for every block reachable from the wait dest, an i1 value
/// encoding the condition under which the block is entered.
struct BlockConditions {
  LogicalResult compute(Block *waitBlock, Block *dest, OpBuilder &builder,
                        Location loc) {
    cond[dest] = constTrue(builder, loc);
    SmallVector<Block *> worklist{dest};
    while (!worklist.empty()) {
      Block *block = worklist.pop_back_val();
      if (block == waitBlock)
        continue;
      auto condBr = dyn_cast<cf::CondBranchOp>(block->getTerminator());
      if (!condBr) {
        if (auto br = dyn_cast<cf::BranchOp>(block->getTerminator())) {
          if (br.getDest() != waitBlock)
            merge(br.getDest(), cond[block], worklist);
        }
        continue;
      }
      Value notCond = comb::XorOp::create(builder, loc, condBr.getCondition(),
                                          constTrue(builder, loc), true);
      merge(condBr.getTrueDest(),
            comb::AndOp::create(builder, loc, cond[block], condBr.getCondition(),
                                true),
            worklist);
      if (condBr.getFalseDest() != waitBlock)
        merge(condBr.getFalseDest(),
              comb::AndOp::create(builder, loc, cond[block], notCond, true),
              worklist);
    }
    return success();
  }

  Value getCondition(Block *block) const {
    auto it = cond.find(block);
    return it == cond.end() ? Value() : it->second;
  }

private:
  void merge(Block *target, Value newCond, SmallVectorImpl<Block *> &worklist) {
    auto it = cond.find(target);
    if (it == cond.end()) {
      cond[target] = newCond;
      worklist.push_back(target);
      return;
    }
    OpBuilder b(target, target->begin());
    it->second = comb::OrOp::create(b, b.getUnknownLoc(), it->second, newCond, true);
  }

  DenseMap<Block *, Value> cond;
};

struct DriveInfo {
  Value clock;
  Value condition;
};

static std::optional<std::pair<Value, ValueRange>>
getIncomingEdge(Block *predecessor, Block *target, OpBuilder &builder,
                Location loc, const BlockConditions &blockConds) {
  Value predecessorCondition = blockConds.getCondition(predecessor);
  if (!predecessorCondition)
    return std::nullopt;
  if (auto branch = dyn_cast<cf::BranchOp>(predecessor->getTerminator())) {
    if (branch.getDest() != target)
      return std::nullopt;
    return std::make_pair(predecessorCondition, branch.getDestOperands());
  }
  auto branch = dyn_cast<cf::CondBranchOp>(predecessor->getTerminator());
  if (!branch)
    return std::nullopt;
  if (branch.getTrueDest() == target)
    return std::make_pair(
        comb::AndOp::create(builder, loc, predecessorCondition,
                            branch.getCondition(), true)
            .getResult(),
        branch.getTrueDestOperands());
  if (branch.getFalseDest() == target) {
    Value notCondition = comb::XorOp::create(
        builder, loc, branch.getCondition(), constTrue(builder, loc), true);
    return std::make_pair(
        comb::AndOp::create(builder, loc, predecessorCondition, notCondition,
                            true)
            .getResult(),
        branch.getFalseDestOperands());
  }
  return std::nullopt;
}

static LogicalResult replaceIntermediateBlockArguments(
    llhd::ProcessOp process, Block *waitBlock, Block *dest,
    const BlockConditions &blockConds, OpBuilder &builder) {
  Location loc = process.getLoc();
  for (Block &block : process.getBody()) {
    if (&block == &process.getBody().front() || &block == waitBlock ||
        &block == dest || block.getNumArguments() == 0)
      continue;
    SmallVector<std::pair<Value, ValueRange>> incoming;
    for (Block *predecessor : block.getPredecessors())
      if (auto edge =
              getIncomingEdge(predecessor, &block, builder, loc, blockConds))
        incoming.push_back(*edge);
    if (incoming.empty())
      return process.emitOpError("intermediate block has no incoming value");
    for (auto argument : llvm::enumerate(block.getArguments())) {
      Value value;
      for (auto &[condition, operands] : incoming) {
        if (argument.index() >= operands.size())
          return process.emitOpError(
              "intermediate branch operand count mismatch");
        Value incomingValue = operands[argument.index()];
        if (incomingValue.getType() != argument.value().getType())
          return process.emitOpError(
              "intermediate branch operand type mismatch");
        if (value)
          value = comb::MuxOp::create(builder, loc, condition, incomingValue,
                                      value);
        else
          value = incomingValue;
      }
      argument.value().replaceAllUsesWith(value);
    }
  }
  return success();
}

static LogicalResult lowerCombinational(
    llhd::CombinationalOp combinational,
    DenseMap<Operation *, DriveInfo> &driveInfos) {
  Location loc = combinational.getLoc();
  OpBuilder builder(combinational);
  BlockConditions blockConds;
  Block *entry = &combinational.getBody().front();
  if (failed(blockConds.compute(nullptr, entry, builder, loc)))
    return combinational.emitOpError("failed to compute block conditions");

  for (Block &block : combinational.getBody()) {
    if (&block == entry || block.getNumArguments() == 0)
      continue;
    SmallVector<std::pair<Value, ValueRange>> incoming;
    for (Block *predecessor : block.getPredecessors())
      if (auto edge =
              getIncomingEdge(predecessor, &block, builder, loc, blockConds))
        incoming.push_back(*edge);
    if (incoming.empty())
      return combinational.emitOpError(
          "combinational block has no incoming value");
    for (auto argument : llvm::enumerate(block.getArguments())) {
      Value value;
      for (auto &[condition, operands] : incoming) {
        if (argument.index() >= operands.size())
          return combinational.emitOpError(
              "combinational branch operand count mismatch");
        Value incomingValue = operands[argument.index()];
        if (incomingValue.getType() != argument.value().getType())
          return combinational.emitOpError(
              "combinational branch operand type mismatch");
        if (value)
          value = comb::MuxOp::create(builder, loc, condition, incomingValue,
                                      value);
        else
          value = incomingValue;
      }
      argument.value().replaceAllUsesWith(value);
    }
  }

  llhd::YieldOp yield;
  for (Block &block : combinational.getBody())
    if (auto candidate = dyn_cast<llhd::YieldOp>(block.getTerminator())) {
      if (yield)
        return combinational.emitOpError("multiple yields are not supported");
      yield = candidate;
    }
  if (!yield ||
      yield.getYieldOperands().size() != combinational.getNumResults())
    return combinational.emitOpError("missing or mismatched yield");
  SmallVector<Value> replacements(yield.getYieldOperands());

  for (Block &block : llvm::make_early_inc_range(combinational.getBody())) {
    Value blockCondition = blockConds.getCondition(&block);
    if (!blockCondition)
      blockCondition = constTrue(builder, loc);
    for (Operation &op : llvm::make_early_inc_range(block)) {
      if (op.hasTrait<OpTrait::IsTerminator>()) {
        op.erase();
        continue;
      }
      if (auto drive = dyn_cast<llhd::DriveOp>(&op)) {
        Value enable = blockCondition;
        if (drive.getEnable())
          enable = comb::AndOp::create(builder, drive.getLoc(), enable,
                                       drive.getEnable(), true);
        builder.setInsertionPoint(combinational);
        auto movedDrive = llhd::DriveOp::create(
            builder, drive.getLoc(), drive.getSignal(), drive.getValue(),
            drive.getTime(), enable);
        driveInfos[movedDrive] = {Value(), enable};
        drive.erase();
        continue;
      }
      op.moveBefore(combinational);
    }
  }
  combinational.replaceAllUsesWith(replacements);
  combinational.erase();
  return success();
}

/// Lower one process into a register bank and splice its body into the
/// module. Returns the clock used by the process, or null on failure.
static Value lowerProcess(llhd::ProcessOp process,
                          DenseMap<Operation *, DriveInfo> &driveInfos) {
  llhd::WaitOp wait;
  for (auto &block : process.getBody()) {
    if (auto candidate = dyn_cast<llhd::WaitOp>(block.getTerminator())) {
      if (wait) {
        process.emitOpError("multiple waits not supported");
        return {};
      }
      wait = candidate;
    }
  }
  if (!wait || !wait.getDest() || wait.getDelay() ||
      wait.getObserved().empty()) {
    process.emitOpError("unsupported process shape");
    return {};
  }

  Block *waitBlock = wait->getBlock();
  Block *dest = wait.getDest();
  Location loc = process.getLoc();
  OpBuilder builder(process);

  // Clock from the first observed value.
  Value clock = wait.getObserved()[0];
  if (!isa<seq::ClockType>(clock.getType()))
    clock = seq::ToClockOp::create(builder, loc, clock);

  // Block conditions for the body (dest onwards, excluding the wait block).
  BlockConditions blockConds;
  if (failed(blockConds.compute(waitBlock, dest, builder, loc))) {
    process.emitOpError("failed to compute block conditions");
    return {};
  }
  if (failed(replaceIntermediateBlockArguments(process, waitBlock, dest,
                                                blockConds, builder)))
    return {};

  // Create the state registers. The branches back to the wait block carry
  // one operand per yield position; extra yielded values that are not block
  // arguments are skipped here and mapped to themselves later. The next
  // value of each state is a mux tree over the predecessors of the wait
  // block (excluding the entry block, which only carries the initial
  // values). The trigger block's false arm is the hold path; its condition
  // is false at every clock edge, so the constant values it passes are never
  // selected.
  SmallVector<Value> registers;
  size_t numState = waitBlock->getArguments().size();
  registers.reserve(numState);
  for (size_t argIdx = 0; argIdx < numState; ++argIdx) {
    // The yield position at which this block argument is yielded.
    size_t yieldIdx = 0;
    bool found = false;
    for (auto yielded : llvm::enumerate(wait.getYieldOperands())) {
      if (yielded.value() == waitBlock->getArgument(argIdx)) {
        yieldIdx = yielded.index();
        found = true;
        break;
      }
    }
    if (!found) {
      process.emitOpError("block argument not found in wait yields");
      return {};
    }

    SmallVector<std::pair<Value, Value>> paths;
    for (Block *pred : waitBlock->getPredecessors()) {
      if (pred->isEntryBlock())
        continue;
      Value cond = blockConds.getCondition(pred);
      Value value;
      auto readOperand = [&](ValueRange operands) -> std::optional<Value> {
        // The frontend emits branches with inconsistent operand lists: some
        // carry one operand per yield position, some one per block argument,
        // and some drop operands. Map by argument position when the counts
        // line up; when the branch carries fewer operands than block
        // arguments, the missing states hold their value.
        if (operands.size() == numState)
          return operands[argIdx];
        if (operands.size() > numState && yieldIdx < operands.size())
          return operands[yieldIdx];
        return std::nullopt;
      };
      if (auto br = dyn_cast<cf::BranchOp>(pred->getTerminator())) {
        auto v = readOperand(br.getDestOperands());
        if (!v) {
          process.emitOpError("branch operand count mismatch");
          return {};
        }
        value = *v;
      } else if (auto condBr =
                     dyn_cast<cf::CondBranchOp>(pred->getTerminator())) {
        auto v = readOperand(condBr.getTrueDest() == waitBlock
                                 ? condBr.getTrueDestOperands()
                                 : condBr.getFalseDestOperands());
        if (!v) {
          process.emitOpError("branch operand count mismatch");
          return {};
        }
        value = *v;
      } else {
        process.emitOpError("unexpected predecessor terminator");
        return {};
      }
      if (!cond) {
        process.emitOpError("unexpected predecessor structure");
        return {};
      }
      paths.push_back({cond, value});
    }
    if (paths.empty()) {
      process.emitOpError("no state update path found");
      return {};
    }
    // Start from the last path with an explicit value; paths without one
    // (missing branch operands) mean the state holds, handled below.
    Value next;
    for (auto &[cond, value] : paths)
      if (value)
        next = value;
    if (!next) {
      process.emitOpError("state has no explicit update path");
      return {};
    }
    bool hasHold = false;
    for (auto &[cond, value] : paths)
      if (!value)
        hasHold = true;
    for (auto it = paths.rbegin(); it != paths.rend(); ++it) {
      if (!it->second)
        continue;
      if (it->second.getType() != next.getType()) {
        process.emitOpError()
            << "state path type mismatch for state " << argIdx << ": "
            << it->second.getType() << " vs " << next.getType();
        return {};
      }
      next = comb::MuxOp::create(builder, loc, it->first, it->second, next);
    }
    auto reg = builder.create<seq::CompRegOp>(loc, next, clock);
    if (hasHold) {
      // Hold paths select the register output; create them after the
      // register exists so the feedback is well-formed.
      Value held = reg;
      for (auto &[cond, value] : paths)
        if (!value)
          held = comb::MuxOp::create(builder, loc, cond, held, held);
      reg.setOperand(0, held);
    }
    registers.push_back(reg);
  }

  // Splice the body into the module: move all ops of the dest block and its
  // successors (excluding the entry and wait blocks) before the process.
  // Replace uses of the wait block arguments with the register outputs and
  // the dest block arguments (the values observed by the wait) with the
  // wait's dest operands. Erase terminators. Record the clock for drives
  // originating from this process so the signal lowering can pick it up.
  for (auto &block : llvm::make_early_inc_range(process.getBody())) {
    if (&block == &process.getBody().front() || &block == waitBlock)
      continue;
    for (auto &op : llvm::make_early_inc_range(block)) {
      if (op.hasTrait<OpTrait::IsTerminator>()) {
        op.erase();
        continue;
      }
      if (auto print = dyn_cast<sim::PrintFormattedProcOp>(&op)) {
        Value condition = blockConds.getCondition(&block);
        if (!condition)
          condition = constTrue(builder, loc);
        builder.setInsertionPoint(process);
        sim::PrintFormattedOp::create(builder, print.getLoc(), print.getInput(),
                                      clock, condition, print.getStream());
        print.erase();
        continue;
      }
      op.moveBefore(process);
      if (auto drive = dyn_cast<llhd::DriveOp>(&op)) {
        Value cond = blockConds.getCondition(&block);
        if (!cond)
          cond = constTrue(builder, loc);
        driveInfos[drive] = {clock, cond};
      }
    }
    if (&block == dest) {
      // Dest block arguments carry the values observed by the wait.
      for (auto [arg, value] :
           llvm::zip(block.getArguments(), wait.getDestOperands()))
        arg.replaceAllUsesWith(value);
    }
  }

  // The wait block itself: move any non-terminator ops and replace its args.
  for (auto &op : llvm::make_early_inc_range(*waitBlock)) {
    if (op.hasTrait<OpTrait::IsTerminator>()) {
      op.erase();
      continue;
    }
    op.moveBefore(process);
  }
  for (auto [arg, reg] : llvm::zip(waitBlock->getArguments(), registers))
    arg.replaceAllUsesWith(reg);

  // Replace the process results with the register outputs. Yields that are
  // wait block arguments map to their register; other yields are values
  // computed at the wait site and map to themselves.
  SmallVector<Value> replacements;
  replacements.reserve(wait.getYieldOperands().size());
  for (Value yielded : wait.getYieldOperands()) {
    if (auto arg = dyn_cast<BlockArgument>(yielded)) {
      if (arg.getOwner() == waitBlock && arg.getArgNumber() < numState)
        replacements.push_back(registers[arg.getArgNumber()]);
      else
        replacements.push_back(yielded);
    } else
      replacements.push_back(yielded);
  }
  process->replaceAllUsesWith(replacements);
  process->erase();
  return clock;
}

/// Rewrite one read-side use of an LLHD reference into an access of an SSA
/// replacement value. Alias chains are followed recursively; drive-side uses
/// are kept until the caller has folded their partial-write semantics.
static void replaceReferenceUse(OpBuilder &builder, Operation *user,
                                Value reference, Value replacement) {
  builder.setInsertionPoint(user);
  Location loc = user->getLoc();

  if (isa<llhd::DriveOp>(user))
    return;
  if (auto probe = dyn_cast<llhd::ProbeOp>(user)) {
    probe.replaceAllUsesWith(replacement);
    probe->erase();
  } else if (auto slice = dyn_cast<llhd::SigArraySliceOp>(user)) {
    Type canonicalType = hw::getCanonicalType(slice.getType());
    auto nestedType = cast<llhd::RefType>(canonicalType).getNestedType();
    auto newSlice = hw::ArraySliceOp::create(builder, loc, nestedType,
                                             replacement,
                                             slice.getLowIndex());
    for (auto *sliceUser : llvm::make_early_inc_range(slice->getUsers())) {
      replaceReferenceUse(builder, sliceUser, slice.getResult(),
                          newSlice.getResult());
    }
    if (slice->use_empty())
      slice->erase();
  } else if (auto get = dyn_cast<llhd::SigArrayGetOp>(user)) {
    auto newGet = builder.create<hw::ArrayGetOp>(loc, replacement,
                                                 get.getIndex());
    for (Operation *getUser : llvm::make_early_inc_range(get->getUsers()))
      replaceReferenceUse(builder, getUser, get.getResult(),
                          newGet.getResult());
    if (get->use_empty())
      get->erase();
  } else if (auto extract = dyn_cast<llhd::SigStructExtractOp>(user)) {
    auto newExtract = builder.create<hw::StructExtractOp>(
        loc, replacement, extract.getFieldAttr());
    for (Operation *extractUser :
         llvm::make_early_inc_range(extract->getUsers()))
      replaceReferenceUse(builder, extractUser, extract.getResult(),
                          newExtract.getResult());
    if (extract->use_empty())
      extract->erase();
  } else if (auto extract = dyn_cast<llhd::SigExtractOp>(user)) {
    auto nestedType = cast<llhd::RefType>(extract.getType()).getNestedType();
    auto shifted = builder.create<comb::ShrUOp>(
        loc, replacement, extract.getLowBit());
    auto newExtract = builder.create<comb::ExtractOp>(
        loc, nestedType, shifted, 0);
    for (Operation *extractUser :
         llvm::make_early_inc_range(extract->getUsers()))
      replaceReferenceUse(builder, extractUser, extract.getResult(),
                          newExtract.getResult());
    if (extract->use_empty())
      extract->erase();
  } else {
    // Fallback: replace the signal operand directly.
    for (unsigned i = 0; i < user->getNumOperands(); ++i)
      if (user->getOperand(i) == reference)
        user->setOperand(i, replacement);
  }
}

static void replaceSignalUse(OpBuilder &builder, Operation *user,
                             llhd::SignalOp sig, Value replacement) {
  replaceReferenceUse(builder, user, sig.getResult(), replacement);
}

/// Return the module-level signal reached through an LLHD reference slice.
/// ImportVerilog commonly drives an aggregate through one or more
/// `llhd.sig.*` aliases.  Treating only a direct `llhd.sig` operand as a drive
/// loses those partial writes and leaves aggregate materialization bitcasts
/// behind later in the HW-to-SystemC pipeline.
static llhd::SignalOp getRootSignal(Value reference) {
  while (Operation *definingOp = reference.getDefiningOp()) {
    if (auto signal = dyn_cast<llhd::SignalOp>(definingOp))
      return signal;
    if (auto slice = dyn_cast<llhd::SigArraySliceOp>(definingOp)) {
      reference = slice.getInput();
      continue;
    }
    if (auto get = dyn_cast<llhd::SigArrayGetOp>(definingOp)) {
      reference = get.getInput();
      continue;
    }
    if (auto extract = dyn_cast<llhd::SigStructExtractOp>(definingOp)) {
      reference = extract.getInput();
      continue;
    }
    if (auto extract = dyn_cast<llhd::SigExtractOp>(definingOp)) {
      reference = extract.getInput();
      continue;
    }
    break;
  }
  return {};
}

static LogicalResult eraseDeadSignalAliases(llhd::SignalOp signal) {
  bool changed = true;
  while (changed) {
    changed = false;
    SmallVector<Operation *> aliases;
    SmallVector<Value> worklist{signal.getResult()};
    while (!worklist.empty()) {
      Value reference = worklist.pop_back_val();
      for (Operation *user : reference.getUsers()) {
        if (!isa<llhd::SigArraySliceOp, llhd::SigArrayGetOp,
                 llhd::SigStructExtractOp, llhd::SigExtractOp>(user))
          continue;
        aliases.push_back(user);
        worklist.append(user->getResults().begin(), user->getResults().end());
      }
    }
    for (Operation *alias : llvm::reverse(aliases)) {
      if (!alias->use_empty())
        continue;
      alias->erase();
      changed = true;
    }
  }
  if (!signal->use_empty())
    return signal.emitOpError("unsupported signal alias remains after lowering");
  signal->erase();
  return success();
}

static bool hasUseInCombinationalRegion(llhd::SignalOp signal) {
  SmallVector<Value> worklist{signal.getResult()};
  while (!worklist.empty()) {
    Value reference = worklist.pop_back_val();
    for (Operation *user : reference.getUsers()) {
      if (user->getParentOfType<llhd::CombinationalOp>())
        return true;
      if (isa<llhd::SigArraySliceOp, llhd::SigArrayGetOp,
              llhd::SigStructExtractOp, llhd::SigExtractOp>(user))
        worklist.append(user->getResults().begin(), user->getResults().end());
    }
  }
  return false;
}

/// Convert the module-level signals into registers or combinational values.
static LogicalResult lowerSignals(hw::HWModuleOp module,
                                  DenseMap<Operation *, DriveInfo> &driveInfos) {
  llvm::SmallVector<llhd::SignalOp> signals(module.getOps<llhd::SignalOp>());

  for (auto sig : signals) {
    OpBuilder builder(sig);
    Location loc = sig.getLoc();

    // `llhd.combinational` has its own control-flow and drive semantics.  Do
    // not partially rewrite a signal observed from such a region; a separate
    // combinational lowering must first hoist those drives and probes.
    if (hasUseInCombinationalRegion(sig))
      continue;

    llvm::SmallVector<llhd::DriveOp> drives;
    bool hasComplexDrive = false;
    for (auto &op : module.getOps()) {
      if (auto drive = dyn_cast<llhd::DriveOp>(&op)) {
        if (getRootSignal(drive.getSignal()) != sig)
          continue;
        drives.push_back(drive);
        hasComplexDrive |= drive.getSignal() != sig.getResult();
      }
    }
    // Determine the clock from the driving processes; require a single
    // clock domain for clocked signals.
    Value clock;
    for (auto drive : drives) {
      auto it = driveInfos.find(drive);
      Value driveClock;
      if (it != driveInfos.end())
        driveClock = it->second.clock;
      else if (hasComplexDrive &&
               drive.getValue().getDefiningOp<seq::CompRegOp>())
        driveClock = drive.getValue().getDefiningOp<seq::CompRegOp>().getClk();
      else if (hasComplexDrive &&
               drive.getValue().getDefiningOp<seq::FirRegOp>())
        driveClock = drive.getValue().getDefiningOp<seq::FirRegOp>().getClk();
      if (!driveClock)
        continue;
      if (clock && clock != driveClock) {
        sig.emitOpError("signal driven from multiple clock domains");
        return failure();
      }
      clock = driveClock;
    }

    if (drives.empty() && !hasComplexDrive) {
      for (auto *user : llvm::make_early_inc_range(sig->getUsers()))
        replaceSignalUse(builder, user, sig, sig.getInit());
      if (failed(eraseDeadSignalAliases(sig)))
        return failure();
      continue;
    }

    // Slice-targeted drives implement partial writes into the signal array.
    // Model them as a per-element update register.
    if (hasComplexDrive) {
      auto canonicalSigType = hw::getCanonicalType(sig.getInit().getType());
      auto arrayType = dyn_cast<hw::ArrayType>(canonicalSigType);
      if (!arrayType)
        continue; // Unsupported shape: leave the signal in place.
      uint64_t numElements = arrayType.getNumElements();
      Type elemType = arrayType.getElementType();
      int64_t elemWidth = hw::getBitWidth(elemType);
      auto indexWidth = std::max(1u, llvm::Log2_64_Ceil(numElements));

      // Create the register from the init and patch its next value after
      // the update mux tree is built.
      seq::CompRegOp reg;
      Value current = sig.getInit();
      if (clock) {
        reg = builder.create<seq::CompRegOp>(loc, sig.getInit(), clock);
        current = reg;
      }
      SmallVector<Value> elems;
      for (uint64_t i = 0; i < numElements; ++i) {
        auto idx = builder.create<hw::ConstantOp>(loc, APInt(indexWidth, i));
        elems.push_back(
            builder.create<hw::ArrayGetOp>(loc, current, idx).getResult());
      }
      for (auto drive : drives) {
        Value enable = drive.getEnable();
        auto infoIt = driveInfos.find(drive);
        if (infoIt != driveInfos.end())
          enable = infoIt->second.condition;
        if (!enable)
          enable = constTrue(builder, loc);
        if (drive.getSignal() == sig.getResult()) {
          for (uint64_t i = 0; i < numElements; ++i) {
            auto idx =
                builder.create<hw::ConstantOp>(loc, APInt(indexWidth, i));
            auto newVal = builder.create<hw::ArrayGetOp>(
                loc, drive.getValue(), idx);
            elems[i] = comb::MuxOp::create(builder, loc, enable, newVal,
                                           elems[i]);
          }
          continue;
        }
        Value low;
        uint64_t sliceLen = 0;
        if (auto sliceOp =
                drive.getSignal().getDefiningOp<llhd::SigArraySliceOp>()) {
          low = sliceOp.getLowIndex();
          Type sliceCanonical = hw::getCanonicalType(sliceOp.getType());
          sliceLen =
              cast<hw::ArrayType>(cast<llhd::RefType>(sliceCanonical)
                                      .getNestedType())
                  .getNumElements();
        } else if (auto getOp =
                       drive.getSignal().getDefiningOp<llhd::SigArrayGetOp>()) {
          low = getOp.getIndex();
          sliceLen = 1;
        } else {
          sig.emitOpError("unexpected complex drive shape");
          return failure();
        }
        for (uint64_t i = 0; i < numElements; ++i) {
          APInt constantLow;
          if (matchPattern(low, m_ConstantInt(&constantLow))) {
            uint64_t lowValue = constantLow.getZExtValue();
            if (i < lowValue || i >= lowValue + sliceLen)
              continue;
          }
          auto iConst =
              builder.create<hw::ConstantOp>(loc, APInt(indexWidth, i));
          auto iSub =
              builder.create<comb::SubOp>(loc, iConst, low).getResult();
          auto inRangeLow =
              comb::ICmpOp::create(builder, loc, comb::ICmpPredicate::uge,
                                   iConst, low)
                  .getResult();
          auto lowPlusLen =
              builder
                  .create<comb::AddOp>(
                      loc, low,
                      builder.create<hw::ConstantOp>(
                          loc, APInt(indexWidth, sliceLen)))
                  .getResult();
          auto inRangeHigh =
              comb::ICmpOp::create(builder, loc, comb::ICmpPredicate::ult,
                                   iConst, lowPlusLen)
                  .getResult();
          auto inRange = comb::AndOp::create(builder, loc, inRangeLow,
                                              inRangeHigh, true);
          Value newVal;
          if (sliceLen == 1 &&
              !isa<hw::ArrayType>(hw::getCanonicalType(
                  drive.getValue().getType())))
            newVal = drive.getValue();
          else {
            auto sliceIndexWidth =
                std::max(1u, llvm::Log2_64_Ceil(sliceLen));
            Value sliceIndex = iSub;
            if (sliceIndex.getType().getIntOrFloatBitWidth() !=
                sliceIndexWidth)
              sliceIndex = builder.create<comb::ExtractOp>(
                  loc, builder.getIntegerType(sliceIndexWidth), sliceIndex, 0);
            newVal =
                builder.create<hw::ArrayGetOp>(loc, drive.getValue(), sliceIndex)
                    .getResult();
          }
          elems[i] = comb::MuxOp::create(
              builder, loc,
              comb::AndOp::create(builder, loc, enable, inRange, true),
              newVal, elems[i]);
        }
      }
      SmallVector<Value> reversed(elems.rbegin(), elems.rend());
      Value next =
          builder.create<hw::ArrayCreateOp>(loc, reversed).getResult();
      Value replacement = next;
      if (reg) {
        reg.setOperand(0, next);
        replacement = reg;
      }

      for (auto *user : llvm::make_early_inc_range(sig->getUsers())) {
        if (isa<llhd::DriveOp>(user))
          continue;
        replaceSignalUse(builder, user, sig, replacement);
      }
      for (auto drive : drives)
        drive->erase();
      if (failed(eraseDeadSignalAliases(sig)))
        return failure();
      continue;
    }

    if (clock) {
      // Clocked register; the enable of each drive is its block condition.

      for (auto drive : drives)
        if (drive.getValue().getType() != sig.getInit().getType())
          return drive.emitOpError("drive value type does not match signal");

      Value next = drives.back().getValue();
      for (auto it = std::next(drives.rbegin()); it != drives.rend(); ++it) {
        Value enable = it->getEnable();
        if (!enable)
          enable = constTrue(builder, loc);
        next = comb::MuxOp::create(builder, loc, enable, it->getValue(), next);
      }
      auto reg = builder.create<seq::CompRegOp>(loc, next, clock);
      for (auto *user : llvm::make_early_inc_range(sig->getUsers())) {
        if (isa<llhd::DriveOp>(user))
          continue;
        replaceSignalUse(builder, user, sig, reg);
      }
      for (auto drive : drives)
        drive->erase();
      if (failed(eraseDeadSignalAliases(sig)))
        return failure();
      continue;
    }

    // Combinational signal: mux over the drives.
    for (auto drive : drives)
      if (drive.getValue().getType() != sig.getInit().getType())
        return drive.emitOpError("drive value type does not match signal");
    Value value = drives.back().getValue();
    for (auto it = std::next(drives.rbegin()); it != drives.rend(); ++it) {
      Value enable = it->getEnable();
      if (!enable)
        enable = constTrue(builder, loc);
      value = comb::MuxOp::create(builder, loc, enable, it->getValue(), value);
    }
    for (auto *user : llvm::make_early_inc_range(sig->getUsers())) {
      if (isa<llhd::DriveOp>(user))
        continue;
      replaceSignalUse(builder, user, sig, value);
    }
    for (auto drive : drives)
      drive->erase();
    if (failed(eraseDeadSignalAliases(sig)))
      return failure();
  }
  return success();
}

struct LowerTimedProcessesPass
    : public circt::llhd::impl::LowerTimedProcessesPassBase<
          LowerTimedProcessesPass> {
  void runOnOperation() override {
    auto module = getOperation();

    DenseMap<Operation *, DriveInfo> driveInfos;
    for (auto process :
         llvm::make_early_inc_range(module.getOps<llhd::ProcessOp>())) {
      if (!lowerProcess(process, driveInfos)) {
        signalPassFailure();
        return;
      }
    }

    for (auto combinational :
         llvm::make_early_inc_range(module.getOps<llhd::CombinationalOp>())) {
      if (failed(lowerCombinational(combinational, driveInfos))) {
        signalPassFailure();
        return;
      }
    }

    if (failed(lowerSignals(module, driveInfos)))
      signalPassFailure();

    // Process bodies are graph regions, while the lowered HW module body is
    // an SSA block.  Moving operations from the former into the latter must
    // therefore restore a topological order.  In particular, a process may
    // contain a value produced in a later CFG block and consumed by an
    // operation in an earlier block.  Leaving the textual block order intact
    // creates use-before-definition IR that is only diagnosed by a later
    // conversion (and often manifests as misleading aggregate type errors).
    // Register feedback is intentionally accepted by the topological sorter;
    // seq.compreg/firreg are the cycle boundaries in this graph region.
    if (!mlir::sortTopologically(module.getBodyBlock())) {
      // A clocked signal can legitimately feed its own next-state expression.
      // That is a semantic feedback edge, not a textual use-before-definition
      // that this pass can eliminate.  The sorter has still moved every
      // acyclic operation into dependency order; leave the remaining cycle for
      // the sequential lowering, which materializes the state signal before
      // evaluating the next-state expression.
      module.emitWarning(
          "timed-process lowering retained a sequential feedback cycle");
    }
  }
};

} // namespace
