//===- LowerTimedProcesses.cpp - LLHD timed process to Seq -----------------===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// Lowers llhd.process operations with a single llhd.wait into Seq registers
// and combinational logic. Targets the code shape generated by ImportVerilog
// for always blocks: a state block terminated by a wait, a dest block that
// checks the trigger condition and loops back to the state block, and drives
// of module-level signals along the body. Processes that do not match this
// shape are left untouched so that callers can diagnose them.
//
// After the processes are lowered, module-level llhd.sig operations driven by
// the spliced process bodies are converted into clocked registers, while
// purely combinationally-driven signals become mux trees.
//
//===----------------------------------------------------------------------===//

#include "circt/Dialect/Comb/CombOps.h"
#include "circt/Dialect/HW/HWOps.h"
#include "circt/Dialect/LLHD/LLHDOps.h"
#include "circt/Dialect/LLHD/LLHDPasses.h"
#include "circt/Dialect/Seq/SeqOps.h"
#include "mlir/Dialect/ControlFlow/IR/ControlFlowOps.h"
#include "mlir/IR/Builders.h"
#include "mlir/Pass/Pass.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/SmallVector.h"

namespace circt {
namespace llhd {
#define GEN_PASS_DEF_LOWERTIMEDPROCESSESPASS
#include "circt/Dialect/LLHD/LLHDPasses.h.inc"
} // namespace llhd
} // namespace circt

using namespace mlir;
using namespace circt;

namespace {

static Value constTrue(OpBuilder &builder, Location loc) {
  return builder.create<hw::ConstantOp>(loc, APInt(1, 1));
}

/// Compute, for every block reachable from the wait dest, an i1 value
/// encoding the condition under which the block is entered.
struct BlockConditions {
  LogicalResult compute(Block *waitBlock, Block *dest, OpBuilder &builder,
                        Location loc) {
    cond[dest] = constTrue(builder, loc);
    SmallVector<Block *> worklist{dest};
    while (!worklist.empty()) {
      Block *block = worklist.pop_back_val();
      if (block == waitBlock)
        continue;
      auto condBr = dyn_cast<cf::CondBranchOp>(block->getTerminator());
      if (!condBr) {
        if (auto br = dyn_cast<cf::BranchOp>(block->getTerminator())) {
          if (br.getDest() != waitBlock)
            merge(br.getDest(), cond[block], worklist);
        }
        continue;
      }
      Value notCond = comb::XorOp::create(builder, loc, condBr.getCondition(),
                                          constTrue(builder, loc), true);
      merge(condBr.getTrueDest(),
            comb::AndOp::create(builder, loc, cond[block], condBr.getCondition(),
                                true),
            worklist);
      if (condBr.getFalseDest() != waitBlock)
        merge(condBr.getFalseDest(),
              comb::AndOp::create(builder, loc, cond[block], notCond, true),
              worklist);
    }
    return success();
  }

  Value getCondition(Block *block) const {
    auto it = cond.find(block);
    return it == cond.end() ? Value() : it->second;
  }

private:
  void merge(Block *target, Value newCond, SmallVectorImpl<Block *> &worklist) {
    auto it = cond.find(target);
    if (it == cond.end()) {
      cond[target] = newCond;
      worklist.push_back(target);
      return;
    }
    OpBuilder b(target, target->begin());
    it->second = comb::OrOp::create(b, b.getUnknownLoc(), it->second, newCond, true);
  }

  DenseMap<Block *, Value> cond;
};

struct DriveInfo {
  Value clock;
  Value condition;
};

/// Lower one process into a register bank and splice its body into the
/// module. Returns the clock used by the process, or null on failure.
static Value lowerProcess(llhd::ProcessOp process,
                          DenseMap<Operation *, DriveInfo> &driveInfos) {
  llhd::WaitOp wait;
  for (auto &block : process.getBody()) {
    if (auto candidate = dyn_cast<llhd::WaitOp>(block.getTerminator())) {
      if (wait) {
        process.emitOpError("multiple waits not supported");
        return {};
      }
      wait = candidate;
    }
  }
  if (!wait || !wait.getDest() || wait.getDelay() ||
      wait.getObserved().empty()) {
    process.emitOpError("unsupported process shape");
    return {};
  }

  Block *waitBlock = wait->getBlock();
  Block *dest = wait.getDest();
  Location loc = process.getLoc();
  OpBuilder builder(process);

  // Clock from the first observed value.
  Value clock = wait.getObserved()[0];
  if (!isa<seq::ClockType>(clock.getType()))
    clock = seq::ToClockOp::create(builder, loc, clock);

  // Block conditions for the body (dest onwards, excluding the wait block).
  BlockConditions blockConds;
  if (failed(blockConds.compute(waitBlock, dest, builder, loc))) {
    process.emitOpError("failed to compute block conditions");
    return {};
  }

  // Create the state registers. The branches back to the wait block carry
  // one operand per yield position; extra yielded values that are not block
  // arguments are skipped here and mapped to themselves later. The next
  // value of each state is a mux tree over the predecessors of the wait
  // block (excluding the entry block, which only carries the initial
  // values). The trigger block's false arm is the hold path; its condition
  // is false at every clock edge, so the constant values it passes are never
  // selected.
  SmallVector<Value> registers;
  size_t numState = waitBlock->getArguments().size();
  registers.reserve(numState);
  for (size_t argIdx = 0; argIdx < numState; ++argIdx) {
    // The yield position at which this block argument is yielded.
    size_t yieldIdx = 0;
    bool found = false;
    for (auto yielded : llvm::enumerate(wait.getYieldOperands())) {
      if (yielded.value() == waitBlock->getArgument(argIdx)) {
        yieldIdx = yielded.index();
        found = true;
        break;
      }
    }
    if (!found) {
      process.emitOpError("block argument not found in wait yields");
      return {};
    }

    SmallVector<std::pair<Value, Value>> paths;
    for (Block *pred : waitBlock->getPredecessors()) {
      if (pred->isEntryBlock())
        continue;
      Value cond = blockConds.getCondition(pred);
      Value value;
      auto readOperand = [&](ValueRange operands) -> std::optional<Value> {
        // The frontend emits branches with inconsistent operand lists: some
        // carry one operand per yield position, some one per block argument,
        // and some drop operands. Map by argument position when the counts
        // line up; when the branch carries fewer operands than block
        // arguments, the missing states hold their value.
        if (operands.size() == numState)
          return operands[argIdx];
        if (operands.size() > numState && yieldIdx < operands.size())
          return operands[yieldIdx];
        return std::nullopt;
      };
      if (auto br = dyn_cast<cf::BranchOp>(pred->getTerminator())) {
        auto v = readOperand(br.getDestOperands());
        if (!v) {
          process.emitOpError("branch operand count mismatch");
          return {};
        }
        value = *v;
      } else if (auto condBr =
                     dyn_cast<cf::CondBranchOp>(pred->getTerminator())) {
        auto v = readOperand(condBr.getTrueDest() == waitBlock
                                 ? condBr.getTrueDestOperands()
                                 : condBr.getFalseDestOperands());
        if (!v) {
          process.emitOpError("branch operand count mismatch");
          return {};
        }
        value = *v;
      } else {
        process.emitOpError("unexpected predecessor terminator");
        return {};
      }
      if (!cond) {
        process.emitOpError("unexpected predecessor structure");
        return {};
      }
      paths.push_back({cond, value});
    }
    if (paths.empty()) {
      process.emitOpError("no state update path found");
      return {};
    }
    // Start from the last path with an explicit value; paths without one
    // (missing branch operands) mean the state holds, handled below.
    Value next;
    for (auto &[cond, value] : paths)
      if (value)
        next = value;
    if (!next) {
      process.emitOpError("state has no explicit update path");
      return {};
    }
    bool hasHold = false;
    for (auto &[cond, value] : paths)
      if (!value)
        hasHold = true;
    for (auto it = paths.rbegin(); it != paths.rend(); ++it) {
      if (!it->second)
        continue;
      if (it->second.getType() != next.getType()) {
        process.emitOpError()
            << "state path type mismatch for state " << argIdx << ": "
            << it->second.getType() << " vs " << next.getType();
        return {};
      }
      next = comb::MuxOp::create(builder, loc, it->first, it->second, next);
    }
    auto reg = builder.create<seq::CompRegOp>(loc, next, clock);
    if (hasHold) {
      // Hold paths select the register output; create them after the
      // register exists so the feedback is well-formed.
      Value held = reg;
      for (auto &[cond, value] : paths)
        if (!value)
          held = comb::MuxOp::create(builder, loc, cond, held, held);
      reg.setOperand(0, held);
    }
    registers.push_back(reg);
  }

  // Splice the body into the module: move all ops of the dest block and its
  // successors (excluding the entry and wait blocks) before the process.
  // Replace uses of the wait block arguments with the register outputs and
  // the dest block arguments (the values observed by the wait) with the
  // wait's dest operands. Erase terminators. Record the clock for drives
  // originating from this process so the signal lowering can pick it up.
  for (auto &block : llvm::make_early_inc_range(process.getBody())) {
    if (&block == &process.getBody().front() || &block == waitBlock)
      continue;
    for (auto &op : llvm::make_early_inc_range(block)) {
      if (op.hasTrait<OpTrait::IsTerminator>()) {
        op.erase();
        continue;
      }
      op.moveBefore(process);
      if (auto drive = dyn_cast<llhd::DriveOp>(&op)) {
        Value cond = blockConds.getCondition(&block);
        if (!cond)
          cond = constTrue(builder, loc);
        driveInfos[drive] = {clock, cond};
      }
    }
    if (&block == dest) {
      // Dest block arguments carry the values observed by the wait.
      for (auto [arg, value] :
           llvm::zip(block.getArguments(), wait.getDestOperands()))
        arg.replaceAllUsesWith(value);
    } else {
      for (auto [arg, reg] : llvm::zip(block.getArguments(), registers))
        arg.replaceAllUsesWith(reg);
    }
  }

  // The wait block itself: move any non-terminator ops and replace its args.
  for (auto &op : llvm::make_early_inc_range(*waitBlock)) {
    if (op.hasTrait<OpTrait::IsTerminator>()) {
      op.erase();
      continue;
    }
    op.moveBefore(process);
  }
  for (auto [arg, reg] : llvm::zip(waitBlock->getArguments(), registers))
    arg.replaceAllUsesWith(reg);

  // Replace the process results with the register outputs. Yields that are
  // wait block arguments map to their register; other yields are values
  // computed at the wait site and map to themselves.
  SmallVector<Value> replacements;
  replacements.reserve(wait.getYieldOperands().size());
  for (Value yielded : wait.getYieldOperands()) {
    if (auto arg = dyn_cast<BlockArgument>(yielded)) {
      if (arg.getOwner() == waitBlock && arg.getArgNumber() < numState)
        replacements.push_back(registers[arg.getArgNumber()]);
      else
        replacements.push_back(yielded);
    } else
      replacements.push_back(yielded);
  }
  process->replaceAllUsesWith(replacements);
  process->erase();
  return clock;
}

/// Rewrite one use of a signal into an access of the replacement value.
static void replaceSignalUse(OpBuilder &builder, Operation *user,
                             llhd::SignalOp sig, Value replacement) {
  builder.setInsertionPoint(user);
  Location loc = user->getLoc();

  if (auto probe = dyn_cast<llhd::ProbeOp>(user)) {
    probe.replaceAllUsesWith(replacement);
    probe->erase();
  } else if (auto slice = dyn_cast<llhd::SigArraySliceOp>(user)) {
    Type canonicalType = hw::getCanonicalType(slice.getType());
    auto nestedType = cast<llhd::RefType>(canonicalType).getNestedType();
    auto newSlice = hw::ArraySliceOp::create(builder, loc, nestedType,
                                             replacement,
                                             slice.getLowIndex());
    // Drives targeting the slice carry partial-write semantics that this
    // lowering does not model; leave those uses untouched so the signal is
    // diagnosed instead of corrupted. Nested sig accesses of the slice are
    // rewritten to hw accesses of the new slice.
    for (auto *sliceUser : llvm::make_early_inc_range(slice->getUsers())) {
      if (isa<llhd::DriveOp>(sliceUser))
        continue;
      if (auto nestedGet = dyn_cast<llhd::SigArrayGetOp>(sliceUser)) {
        auto newGet = builder.create<hw::ArrayGetOp>(
            loc, newSlice.getResult(), nestedGet.getIndex());
        nestedGet.replaceAllUsesWith(newGet.getResult());
        nestedGet->erase();
        continue;
      }
      sliceUser->replaceUsesOfWith(slice, newSlice.getResult());
    }
    slice->erase();
  } else if (auto get = dyn_cast<llhd::SigArrayGetOp>(user)) {
    auto newGet = builder.create<hw::ArrayGetOp>(loc, replacement,
                                                 get.getIndex());
    get.replaceAllUsesWith(newGet.getResult());
    get->erase();
  } else {
    // Fallback: replace the signal operand directly.
    for (unsigned i = 0; i < user->getNumOperands(); ++i)
      if (user->getOperand(i) == sig)
        user->setOperand(i, replacement);
  }
}

/// Convert the module-level signals into registers or combinational values.
static LogicalResult lowerSignals(hw::HWModuleOp module,
                                  DenseMap<Operation *, DriveInfo> &driveInfos) {
  llvm::SmallVector<llhd::SignalOp> signals(module.getOps<llhd::SignalOp>());

  for (auto sig : signals) {
    OpBuilder builder(sig);
    Location loc = sig.getLoc();

    llvm::SmallVector<llhd::DriveOp> drives;
    bool hasComplexDrive = false;
    for (auto &op : module.getOps()) {
      if (auto drive = dyn_cast<llhd::DriveOp>(&op)) {
        if (drive.getSignal() == sig)
          drives.push_back(drive);
        else if (auto sliceOp =
                     drive.getSignal().getDefiningOp<llhd::SigArraySliceOp>())
          if (sliceOp.getInput() == sig)
            hasComplexDrive = true;
      }
    }
    // Determine the clock from the driving processes; require a single
    // clock domain for clocked signals.
    Value clock;
    for (auto drive : drives) {
      auto it = driveInfos.find(drive);
      if (it == driveInfos.end())
        continue;
      if (clock && clock != it->second.clock) {
        sig.emitOpError("signal driven from multiple clock domains");
        return failure();
      }
      clock = it->second.clock;
    }

    if (drives.empty() && !hasComplexDrive) {
      sig.replaceAllUsesWith(sig.getInit());
      sig->erase();
      continue;
    }

    // Slice-targeted drives implement partial writes into the signal array.
    // Model them as a per-element update register.
    if (hasComplexDrive) {
      auto canonicalSigType = hw::getCanonicalType(sig.getInit().getType());
      auto arrayType = dyn_cast<hw::ArrayType>(canonicalSigType);
      if (!arrayType || !clock)
        continue; // Unsupported shape: leave the signal in place.
      uint64_t numElements = arrayType.getNumElements();
      Type elemType = arrayType.getElementType();
      int64_t elemWidth = hw::getBitWidth(elemType);
      auto indexWidth = std::max(1u, llvm::Log2_64_Ceil(numElements));

      // Create the register from the init and patch its next value after
      // the update mux tree is built.
      auto reg = builder.create<seq::CompRegOp>(loc, sig.getInit(), clock);
      Value current = reg;
      SmallVector<Value> elems;
      for (uint64_t i = 0; i < numElements; ++i) {
        auto idx = builder.create<hw::ConstantOp>(loc, APInt(indexWidth, i));
        elems.push_back(
            builder.create<hw::ArrayGetOp>(loc, current, idx).getResult());
      }
      for (auto drive : drives) {
        Value enable = drive.getEnable();
        auto infoIt = driveInfos.find(drive);
        if (infoIt != driveInfos.end())
          enable = infoIt->second.condition;
        if (!enable)
          enable = constTrue(builder, loc);
        Value low;
        uint64_t sliceLen = 0;
        if (auto sliceOp =
                drive.getSignal().getDefiningOp<llhd::SigArraySliceOp>()) {
          low = sliceOp.getLowIndex();
          Type sliceCanonical = hw::getCanonicalType(sliceOp.getType());
          sliceLen =
              cast<hw::ArrayType>(cast<llhd::RefType>(sliceCanonical)
                                      .getNestedType())
                  .getNumElements();
        } else if (auto getOp =
                       drive.getSignal().getDefiningOp<llhd::SigArrayGetOp>()) {
          low = getOp.getIndex();
          sliceLen = 1;
        } else {
          sig.emitOpError("unexpected complex drive shape");
          return failure();
        }
        for (uint64_t i = 0; i < numElements; ++i) {
          auto iConst =
              builder.create<hw::ConstantOp>(loc, APInt(indexWidth, i));
          auto iSub =
              builder.create<comb::SubOp>(loc, iConst, low).getResult();
          auto inRangeLow =
              comb::ICmpOp::create(builder, loc, comb::ICmpPredicate::uge,
                                   iConst, low)
                  .getResult();
          auto lowPlusLen =
              builder
                  .create<comb::AddOp>(
                      loc, low,
                      builder.create<hw::ConstantOp>(
                          loc, APInt(indexWidth, sliceLen)))
                  .getResult();
          auto inRangeHigh =
              comb::ICmpOp::create(builder, loc, comb::ICmpPredicate::ult,
                                   iConst, lowPlusLen)
                  .getResult();
          auto inRange = comb::AndOp::create(builder, loc, inRangeLow,
                                              inRangeHigh, true);
          Value newVal;
          if (sliceLen == 1)
            newVal = drive.getValue();
          else
            newVal =
                builder.create<hw::ArrayGetOp>(loc, drive.getValue(), iSub)
                    .getResult();
          elems[i] = comb::MuxOp::create(
              builder, loc,
              comb::AndOp::create(builder, loc, enable, inRange, true),
              newVal, elems[i]);
        }
      }
      SmallVector<Value> reversed(elems.rbegin(), elems.rend());
      Value next =
          builder.create<hw::ArrayCreateOp>(loc, reversed).getResult();
      reg.setOperand(0, next);

      for (auto *user : llvm::make_early_inc_range(sig->getUsers())) {
        if (isa<llhd::DriveOp>(user))
          continue;
        replaceSignalUse(builder, user, sig, reg);
      }
      for (auto drive : drives)
        drive->erase();
      sig->erase();
      continue;
    }

    if (clock) {
      // Clocked register; the enable of each drive is its block condition.

      Value next = drives.back().getValue();
      for (auto it = std::next(drives.rbegin()); it != drives.rend(); ++it) {
        Value enable = it->getEnable();
        if (!enable)
          enable = constTrue(builder, loc);
        next = comb::MuxOp::create(builder, loc, enable, it->getValue(), next);
      }
      auto reg = builder.create<seq::CompRegOp>(loc, next, clock);
      for (auto *user : llvm::make_early_inc_range(sig->getUsers())) {
        if (isa<llhd::DriveOp>(user))
          continue;
        replaceSignalUse(builder, user, sig, reg);
      }
      for (auto drive : drives)
        drive->erase();
      sig->erase();
      continue;
    }

    // Combinational signal: mux over the drives.
    Value value = drives.back().getValue();
    for (auto it = std::next(drives.rbegin()); it != drives.rend(); ++it) {
      Value enable = it->getEnable();
      if (!enable)
        enable = constTrue(builder, loc);
      value = comb::MuxOp::create(builder, loc, enable, it->getValue(), value);
    }
    for (auto *user : llvm::make_early_inc_range(sig->getUsers())) {
      if (isa<llhd::DriveOp>(user))
        continue;
      replaceSignalUse(builder, user, sig, value);
    }
    for (auto drive : drives)
      drive->erase();
    sig->erase();
  }
  return success();
}

struct LowerTimedProcessesPass
    : public circt::llhd::impl::LowerTimedProcessesPassBase<
          LowerTimedProcessesPass> {
  void runOnOperation() override {
    auto module = getOperation();

    DenseMap<Operation *, DriveInfo> driveInfos;
    for (auto process :
         llvm::make_early_inc_range(module.getOps<llhd::ProcessOp>())) {
      if (!lowerProcess(process, driveInfos)) {
        signalPassFailure();
        return;
      }
    }

    if (failed(lowerSignals(module, driveInfos)))
      signalPassFailure();
  }
};

} // namespace
